In [1]:
import numpy as np
n0=np.array([1,2,3])
n1=np.array([[1,2,3],[4,5,6]],float)
n2=np.array([[2,3,4],[5,6,7]],float)
n3= np.array([[8],[9],[10]])
n4= np.array([[[1],[2]], [[3],[4]]])
n5= np.array([[[[1],[2]], [[3],[4]]],
            [[[5],[6]], [[7],[8]]]])

print(n0.shape,n0.ndim, len(n0))
print(n1.shape,n1.ndim, len(n1))
print(n3.shape,n3.ndim, len(n3))
print(n4.shape,n4.ndim,len(n4))
print(n5,n5.shape,n5.ndim, n5.itemsize,  n5.size, n5.dtype.name, type(n5))

(3,) 1 3
(2, 3) 2 2
(3, 1) 2 3
(2, 2, 1) 3 2
[[[[1]
   [2]]

  [[3]
   [4]]]


 [[[5]
   [6]]

  [[7]
   [8]]]] (2, 2, 2, 1) 4 4 8 int32 <class 'numpy.ndarray'>


In [2]:
n1*n2

array([[ 2.,  6., 12.],
       [20., 30., 42.]])

In [3]:
print(np.mean(n1))

3.5


In [4]:
print(np.dot(n1,n3))
print(n1*n2)

[[ 56.]
 [137.]]
[[ 2.  6. 12.]
 [20. 30. 42.]]


In [5]:
a=range(10)
%timeit [i**2 for i in a]
b= np.arange(10).reshape(2,5)
%timeit b**2

4.39 µs ± 243 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
841 ns ± 24.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
np.array?
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [13]:
a=np.arange(10)
print(a)
b=np.arange(0,9,1)
print(b)
c=np.linspace(0,1,6)#, endpoint=False)
print(c)
d=np.array([1,2,3], float)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]
[0.  0.2 0.4 0.6 0.8 1. ]
[1. 2. 3.]


In [8]:
print(np.ones((2,3)))
print(np.zeros((2,3)))
print("\n",np.eye((3)))
print("\n",np.diag(np.array([1,2,3,4])))
print("\n", np.empty((2,3), int))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

 [[         0 1072693248          0]
 [1072693248          0 1072693248]]


In [9]:
n1.sum(axis=0)
print(n1.cumsum(axis=1))

[[ 1.  3.  6.]
 [ 4.  9. 15.]]


In [24]:
a= np.linspace(0,2,3)
a= np.arange(10)
print(a)
print(a[::-1]) 
a[2:5:2] #[start;end:step]
a[::2]#ervery two steps


[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


IndexError: too many indices for array

In [28]:
c=a[::2]
np.may_share_memory(a,c)
a[0]=12
c

array([12,  2,  4,  6,  8])

In [32]:
d=a[::2].copy()
np.may_share_memory(a,d)
a[2]=14
d

array([12,  2,  4,  6,  8])

In [41]:
np.random.seed(3)
a=np.random.randint(0,100,10)
mask=a % 3==0
mask
print(a[mask])
a[mask]=-1
print(a)

[24  3 72  0 21]
[-1 -1 56 -1 -1 -1 19 74 41 10]


In [43]:
print(a[[2,4,2,6,2]])#from list of index
a[[3,5]]=-4
a

[56 -1 56 19 56]


array([-1, -1, 56, -4, -1, -4, 19, 74, 41, 10])

In [61]:
arr=np.array([np.random.randint(0,10,10), np.random.randint(0,10,10)])
print(arr)
print(arr.shape)
n=np.arange(40)
n[arr]
print(n)

[[0 8 7 1 2 5 2 7 6 7]
 [9 1 5 7 5 9 7 2 6 4]]
(2, 10)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [56]:
np.random.randint(0,10,10)

array([1, 7, 8, 7, 4, 0, 0, 4, 3, 0])

In [65]:
import pandas as pd
data = {"year": [1,2,3,4],
       "team": ['a','b','c','d']}
df=pd.DataFrame(data)
df.dtypes

team    object
year     int64
dtype: object